### ISSUE TITLE
Not throwing exception on "Error: getaddrinfo ENOTFOUND"

### ISSUE THREAD

**Issue by alexdpoon** [lmammino/tall#11]
When using tall() inside a try/catch block, the following kind of error isn't thrown and catchable, but instead, the node process exits with:

Error: getaddrinfo ENOTFOUND XXXXXX XXXXXX
 at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)

**Comment by alexdpoon** [comment]
Also, if this helps, the original URL was a bit.ly that redirects to an amazon ec2 aws url with port 8080, as in:

http://ec2-xx-xxx-xxx-xx.us-east-2.compute.amazonaws.com:8080/login

The 8080 is probably not being handled by tall correctly.

**Comment by lmammino** [comment]
Hello @alexdpoon, thanks for opening this issue. I just opened a [PR](#12) that should address this issue, can you please review/validate it?

**Comment by alexdpoon** [comment]
Thanks, looks good.

**Comment by lmammino** [comment]
Version 2.2 was just published with this fix.

Thanks again @alexdpoon
