### ISSUE TITLE
Not throwing catchable error so node process exits

### ISSUE THREAD

**Issue by alexdpoon** [lmammino/tall#14]
When using tall() inside a try/catch block, the following kind of error isn't thrown and catchable, but instead, the node process exits with:

Error: connect ETIMEDOUT 216.70.100.245:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

The URL was http://bit.ly/nitioninfo

Using tall v2.2.0

**Comment by lmammino** [comment]
Closed by #15
