### ISSUE TITLE
Feature request: Detect whether returned URL is final URL or another short URL

### ISSUE THREAD

**Issue by phocks** [lmammino/tall#2]
Often times the tall URL is a link to another URL shortening service. It would be good to be able to return the conclusive final URL.

**Comment by lmammino** [comment]
Hi @phocks!
First of all, thanks for trying this library.

This is definitely a good idea. I am a bit concerned about the possibility to do too many requests (redirects) but I'll see if there's some easy way around it.

**Comment by lmammino** [comment]
This is now done in `v2.0.0`. Let me know if it works for you :)

**Comment by phocks** [comment]
Brilliant! Thanks so much. I will give it a go!
