### ISSUE TITLE
Support following <meta http-equiv="refresh" /> ?

### ISSUE THREAD

**Issue by karlhorky** [lmammino/tall#42]
Hi @lmammino 👋

First of all, thanks so much for creating and maintaining this module, super simple and works!

What are your thoughts on supporting unshortening the `<meta http-equiv="refresh" />` redirects that pages can return in the response body?

For example, the html below would instantly redirect to `https://example.com/abc/`:

```html
<html>
  <head>
    <meta http-equiv="refresh" content="0;url=https://example.com/abc/">
  </head>
  <body></body>
</html>
```

**Comment by lmammino** [comment]
Hello @karlhorky. Thanks for the kind feedback. It's great to know that you enjoy using this library.

I think this feature makes sense but it might require introducing external dependencies for parsing HTML. One of the core principles of this library is to be small and dependency-less, so I'd like to think of an approach that makes this feature optional keeping the core small for users who don't need it.

The first thing that comes to mind is to implement a simple plugin system that allows for external hooks. This way users who want this feature will install the extra plugin package (and get related additional dependencies with it).

What do you think? Andy would you be interested in contributing?

**Comment by karlhorky** [comment]
Added a first naïve (strawman) implementation here: #43
