### ISSUE TITLE
Tiktok links not resolving?

### ISSUE THREAD

**Issue by txj-xyz** [lmammino/tall#45]
Hey, just using this package to resolve TikTok links and it appears that `tall` is not working for those links

![](https://cdn.discordapp.com/attachments/918670717753630822/946057706077298758/vrUmQl83lvByePAYbrXG.png)

**Comment by lmammino** [comment]
I had a quick look at this and it does not seem like an issue with `tall`.

What's happening is that tiktok's servers seems to hang the connection if you are not providing a user-agent in the headers.

This seems to work:

```js
const {tall} = require("tall")

tall('https://vm.tiktok.com/TTPdBsSRy1', {
  headers: {
    'User-Agent': 'curl/7.77.0'
  }
})
  .then(console.log)
  .catch(console.error)
```

output:

```plain
https://www.tiktok.com/@friendofabanana/video/7063452052835470639?_t=8PysqXgPRfS&_r=1
```

Let me know if this solves the issue for you
