### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by grinono** [lmammino/tall#5]
following: http://www.awin1.com/awclick.php?mid=8061&id=451975',
returns:
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)

**Comment by grinono** [comment]
moved to node-fetch to get the redirect links of a few 1000 pages. it's working just fine.

const unshortenedUrl = await fetch(deepLink)

**Comment by alexdpoon** [comment]
It's rare, but I get "Error: unable to verify the first certificate" once in a while, and my node app exits out rather than catching an exception:

Reproducible example:

`await tall('http://bit.ly/ExperienceCenterFR') 
`

results in:

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1051:34)
    at TLSSocket.emit (events.js:189:13)
    at TLSSocket.EventEmitter.emit (domain.js:441:20)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
```

Using latest version 2.2.

**Comment by lmammino** [comment]
Two possible ways to solve this:

- set `process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0` (which you can do without code changes).

- change the code and add the options:

```javascript
tls: {
     // do not fail on invalid certs
     rejectUnauthorized: false
}
```

**Comment by lmammino** [comment]
Closing this one. Let me know if you still have this issue
