### ISSUE TITLE
Array of urls not able to resolved

### ISSUE THREAD

**Issue by nintendoMan** [lmammino/tall#6]
Hi,

As investigating while trying to get this work with array of urls => does not work?
If there is a away to do it, write it down?

Simple as but not able to get it work.

**Comment by fiblan** [comment]
A solution could be use Promise.all + map. I'm sure that you could write it cleaner...

```
var tall = require('tall').default

var urlArray = [
  'http://loige.link/b',
  'http://loige.link/gh',
  'http://loige.link/codemotion-rome-2017'
 ];

async function tallMultiple(arrayUrl) {
  try {
    let unshortenedUrls = await Promise.all(urlArray.map(async (item) =>{return await tall(item)}))
    console.log(unshortenedUrls);
  } catch( err) {
    console.error('AAAW 👻', err)
  }
}

tallMultiple(urlArray)
```

**Comment by lmammino** [comment]
Tall already returns a promise, so you can rewrite the above proposal by @fiblan as follows (untested):

```javascript
var tall = require('tall').default

const tallMany = (urls) => Promise.all( urls.map( url => tall(url) ) )


async function main() {
  const urls = [
    'http://loige.link/b',
    'http://loige.link/gh',
    'http://loige.link/codemotion-rome-2017'
  ]

  const expandendUrls = await tallMany(urls)
  console.log(expandendUrls)
}

main()
```

Is this such a common use case to make sense to introduce something like `tallMany` here in the library itself?

In any case, let me know if this works for you :)

**Comment by lmammino** [comment]
Closing this one. Le t me know if you still have issues
